### ISSUE TITLE
Production checklist

### ISSUE THREAD

**Issue by bion** [seattle-uat/civiform#742]
Technical work needed before allowing applicant traffic to production.

- [x] server logs are sent to city of Seattle centralized logging service
- [x] deployment configures an appropriate number of server threads based on (v)CPU threads
- [x] automated database backups are configured
- [ ] the site offers some means of contacting technical support
- [x] non-city employees are unable to access the production database
- [x] basic traffic monitoring is available -- QPS, error ratios split out by 4xx and 5xx level errors
- [x] basic probers run in production (it may be that probers that mutate state are infeasible in prod)
- [x] domain and https cert are configured by the city.
- [x] complete security tasks (#363, #364, #365)
- [x] set up google analytics (#574, #575)
- [x] redirect http requests to https
- [ ] redirect `www.` to the bare domain or vice-versa

**Comment by neel-a-mehta** [comment]
Are the security-related topics (#363, #364, #365) fair game for this too?

**Comment by lianne-oy** [comment]
the site offers some means of contacting technical support - not needed until Phase 2 (public links working) - using pilot escalation path in phase 1 https://seattlegov.sharepoint.com/:w:/r/sites/IAC-EXT/AP/_layouts/15/Doc.aspx?sourcedoc=%7BF5ED3858-CD8F-4C7A-839B-FE6FB45CF8AB%7D&file=User%20Issue%20Escalation%20Path%20for%20CiviForm%20Pilot.docx&action=default&mobileredirect=true

automated database backups are configured - Still need to check

**Comment by lianne-oy** [comment]
redirect www. to the bare domain or vice-versa - NICE TO HAVE; NOT NEEDED
the site offers some means of contacting technical support - STILL NEED.  Configuration setting for email address at bottom page / footer.  Need email address from City.

**Comment by bion** [comment]
Closing this with one work item remaining and captured here: https://github.com/seattle-uat/civiform/issues/1308
